service: markdown

package:
  exclude:
    - node_modules/**
    - ./**
  include:
    - server/**

custom:
  serverless-offline:
    port: 4000
  config: ${file(./serverlessconfig.yml)}

plugins:
  - serverless-secrets
  - serverless-plugin-include-dependencies
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.config.deployment}
  region: ${self:custom.config.aws.region}

  environment:
    DEPLOYMENT: ${self:provider.stage}
    REGION: ${self:provider.region}
    TABLE: ${self:custom.config.aws.table_name}
    ALLOW_ORIGIN: ${self:custom.config.origins.${self:custom.config.deployment}}

  environmentSecrets:
    CAPTCHA_SECRET_KEY: "CAPTCHA_SECRET_KEY"

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE}"

functions:
  fetch:
    handler: server/handlers.getHandler
    events:
      - http:
          path: ${self:service}/fetch
          method: post
          resp: json
          cors:
            origin: ${self:provider.environment.ALLOW_ORIGIN}
            headers:
              - Content-Type
              - Origin
              - Accept
  submit:
    handler: server/handlers.postHandler
    events:
      - http:
          path: ${self:service}/submit
          method: post
          resp: json
          cors:
            origin: ${self:provider.environment.ALLOW_ORIGIN}
            headers:
              - Content-Type
              - Origin
              - Accept
  flush:
    handler: server/handlers.cleanupHandler
    events:
      - http:
          path: ${self:service}/flush
          method: post
          resp: json
          cors: true

#  cleanup:
#    handler: server/handlers.cleanupHandler
#    events:
#      - schedule:
#          name: tableCleanupSchedule
#          description: "Deletes entries from a table that are over 24 hours old"
#          rate: rate(10 seconds)

resources:
  Resources:
    MarkdownTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
         - AttributeName: id
           AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.TABLE}
